-- 1. Create Users Table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'FISHERMAN',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Insert default admin
INSERT INTO users (username, password, role) 
VALUES ('Admin', '1234', 'Admin');

-- 2. Create Catches Table
CREATE TABLE IF NOT EXISTS catches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fisherman TEXT NOT NULL,
    fish_type TEXT NOT NULL,
    weight DECIMAL(10,2) NOT NULL,
    price_per_kg DECIMAL(10,2) NOT NULL,
    total_value DECIMAL(10,2) NOT NULL,
    status TEXT DEFAULT 'RECORDED',
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Create Operational Expenses Table
CREATE TABLE IF NOT EXISTS operational_expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    category TEXT DEFAULT 'General',
    recorded_by TEXT NOT NULL,
    role TEXT NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Create Settings Table
CREATE TABLE IF NOT EXISTS settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prices JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Insert default prices
INSERT INTO settings (id, prices) VALUES (1, '{
    "Tuna": 150, 
    "lumayagan": 150, 
    "Big Karaw": 150, 
    "Perit": 150, 
    "Tulingan": 150, 
    "MC": 150
}');

-- Enable Real-time for all tables
ALTER PUBLICATION supabase_realtime ADD TABLE users;
ALTER PUBLICATION supabase_realtime ADD TABLE catches;
ALTER PUBLICATION supabase_realtime ADD TABLE operational_expenses;
ALTER PUBLICATION supabase_realtime ADD TABLE settings;
